export interface ToolMeta {
  id: string;
  tag: string;
  title: string;
  shortDesc: string;
  category: "convert" | "optimize" | "edit" | "meta" | "document";
  href: string;
  featured?: boolean;
  popular?: boolean;
  badge?: string;
  shortcut?: string;
  metricsLabel?: string;
  features: string[];
}

export const TOOLS: ToolMeta[] = [
  {
    id: "image-converter",
    tag: "01",
    title: "Image Converter",
    shortDesc: "Batch convert between PNG, JPG, WebP, AVIF, and BMP format with quality and compression controls.",
    category: "convert",
    href: "/tools/image-converter",
    featured: true,
    popular: true,
    badge: "Multi-Format",
    shortcut: "C",
    metricsLabel: "5 formats · Batch ready",
    features: ["Batch convert", "PNG / JPG / WebP / AVIF / BMP", "Quality control", "Instant zip export"],
  },
  {
    id: "image-compressor",
    tag: "02",
    title: "Image Compressor",
    shortDesc: "Reduce image size up to 80% with interactive before/after visual comparison slider and batch compression.",
    category: "optimize",
    href: "/tools/image-compressor",
    featured: true,
    popular: true,
    badge: "Popular",
    shortcut: "K",
    metricsLabel: "Up to 80% reduction",
    features: ["Visual before/after slider", "Custom quality & presets", "Batch compression", "Original vs new size stats"],
  },
  {
    id: "svg-tools",
    tag: "03",
    title: "SVG Studio & Vectorizer",
    shortDesc: "Render SVG to hi-res PNG/JPG, optimize SVG markup, or trace raster images into real vector paths.",
    category: "convert",
    href: "/tools/svg-tools",
    featured: true,
    popular: true,
    badge: "Vector Suite",
    shortcut: "S",
    metricsLabel: "Retina @3x · True paths",
    features: ["SVG to PNG / JPG / WebP", "SVG optimizer & cleaner", "True vector contour tracing", "Retina scale multiplier"],
  },
  {
    id: "image-resizer",
    tag: "04",
    title: "Image Resizer",
    shortDesc: "Resize images to exact dimensions, aspect ratio locks, or social media presets.",
    category: "edit",
    href: "/tools/image-resizer",
    popular: true,
    shortcut: "R",
    metricsLabel: "Aspect ratio lock · Presets",
    features: ["Aspect ratio lock", "Social presets (1080p, IG, Story)", "Percentage scaling", "Batch resize"],
  },
  {
    id: "image-cropper",
    tag: "05",
    title: "Image Cropper",
    shortDesc: "Visual crop interface with handles, fixed aspect ratios (1:1, 16:9, 4:3), zoom, and rule-of-thirds grid.",
    category: "edit",
    href: "/tools/image-cropper",
    popular: true,
    shortcut: "X",
    metricsLabel: "1:1, 16:9, 4:3 · Grid",
    features: ["Freeform & fixed ratios (1:1, 16:9, 4:3)", "Interactive handles", "Zoom & rotate", "Instant export"],
  },
  {
    id: "image-rotate-flip",
    tag: "06",
    title: "Rotate & Flip",
    shortDesc: "Quickly rotate 90°, 180°, or mirror horizontally and vertically with instant canvas export.",
    category: "edit",
    href: "/tools/image-rotate-flip",
    shortcut: "T",
    metricsLabel: "90° CW/CCW · Flip H/V",
    features: ["90° CW / CCW & 180°", "Horizontal & vertical flip", "Arbitrary angle slider", "Batch rotation"],
  },
  {
    id: "metadata",
    tag: "07",
    title: "EXIF & Metadata",
    shortDesc: "Inspect camera settings, exposure, and GPS location tags with one-click metadata removal.",
    category: "meta",
    href: "/tools/metadata",
    badge: "Privacy",
    shortcut: "M",
    metricsLabel: "GPS & camera tags · Sanitize",
    features: ["Camera & lens data", "Exposure, ISO, Aperture", "GPS map link", "One-click sanitize & strip"],
  },
  {
    id: "image-to-pdf",
    tag: "08",
    title: "Image → PDF",
    shortDesc: "Bundle images into a single PDF document with page sizes (A4, Letter, Fit), orientation, and margins.",
    category: "document",
    href: "/tools/image-to-pdf",
    popular: true,
    shortcut: "P",
    metricsLabel: "A4, Letter · Reorderable",
    features: ["A4, Letter, Fit to image", "Custom page margins", "Drag/move ordering", "Instant PDF download"],
  },
  {
    id: "pdf-to-image",
    tag: "09",
    title: "PDF → Image",
    shortDesc: "Extract PDF pages as high-resolution PNG, JPG, or WebP images individually or as a ZIP archive.",
    category: "document",
    href: "/tools/pdf-to-image",
    popular: true,
    shortcut: "D",
    metricsLabel: "Up to 300 DPI · ZIP export",
    features: ["High-res rendering (up to 3x)", "Page selector", "Individual or zip export", "100% private in browser"],
  },
  {
    id: "watermark",
    tag: "10",
    title: "Image Watermark",
    shortDesc: "Add customizable text or logo image watermarks with 9-anchor positioning and tile patterns.",
    category: "edit",
    href: "/tools/watermark",
    shortcut: "W",
    metricsLabel: "Text & logo · Tile pattern",
    features: ["Text & logo watermarks", "9 placement positions + tile", "Opacity & rotation", "Batch watermarking"],
  },
  {
    id: "background",
    tag: "11",
    title: "Background Tools",
    shortDesc: "Sample any background color with the eyedropper to replace it with transparency or solid colors.",
    category: "edit",
    href: "/tools/background",
    shortcut: "B",
    metricsLabel: "Chroma key · Transparent PNG",
    features: ["Chroma / color keying", "Eyedropper sampler", "Tolerance & feathering", "Transparent export"],
  },
  {
    id: "base64",
    tag: "12",
    title: "Base64 Converter",
    shortDesc: "Encode images into Data URIs, HTML <img>, and CSS snippets, or decode Base64 back into image files.",
    category: "convert",
    href: "/tools/base64",
    shortcut: "6",
    metricsLabel: "HTML, CSS & Data URI",
    features: ["Image to Base64 URI", "HTML <img> & CSS code snippets", "Base64 string to image file", "One-click copy"],
  },
  {
    id: "image-info",
    tag: "13",
    title: "Image Info & Palette",
    shortDesc: "Inspect dimensions, aspect ratio, megapixels, transparency, and extract dominant color palette.",
    category: "meta",
    href: "/tools/image-info",
    shortcut: "I",
    metricsLabel: "Palette extraction · Megapixels",
    features: ["Megapixel & aspect ratio", "Dominant color palette with hex copy", "Alpha channel detection", "Direct tool shortcuts"],
  },
  {
    id: "favicon-generator",
    tag: "14",
    title: "Favicon Generator",
    shortDesc: "Generate multi-resolution favicon.ico (16/32/48px), Apple Touch, Android Chrome icons, webmanifest and ZIP package.",
    category: "convert",
    href: "/tools/favicon-generator",
    featured: true,
    popular: true,
    badge: "ICO & ZIP",
    shortcut: "F",
    metricsLabel: "16–512px · ZIP & Manifest",
    features: [
      "Multi-resolution favicon.ico",
      "Apple Touch & Android Chrome PNGs",
      "site.webmanifest generator",
      "1-Click ZIP bundle download",
    ],
  },
  {
    id: "svg-viewer",
    tag: "15",
    title: "SVG Viewer & Editor",
    shortDesc: "Paste SVG code directly, live inspect and edit markup, swap colors, and save as optimized SVG or hi-res PNG.",
    category: "convert",
    href: "/tools/svg-viewer",
    featured: true,
    popular: true,
    badge: "Live Editor",
    shortcut: "V",
    metricsLabel: "Live render · Code editor · Save",
    features: [
      "Direct SVG code pasting & live editor",
      "Syntax validation & error detection",
      "Color palette detection & instant swap",
      "Save as SVG, PNG (1-4x), and JSX",
    ],
  },
];

export const TOOL_CATEGORIES = [
  { id: "all", label: "All Tools" },
  { id: "convert", label: "Convert & SVG" },
  { id: "optimize", label: "Compress" },
  { id: "edit", label: "Edit & Transform" },
  { id: "document", label: "PDF & Document" },
  { id: "meta", label: "Metadata & Info" },
] as const;
